### ISSUE TITLE
main.c:66:13: warning: incompatible pointer types passing 'char *[20]' to parameter of type 'char *'

### ISSUE THREAD

**Issue by foxweb** [foxweb/pico#15]
https://github.com/foxweb/pico/blob/master/main.c#L65

When I use definition `char *index_html;` — this pointer has undefined value and causes HTTP-response failure.
Renaming doesn't help.

When I specify the length of the string — `char *index_html[20];` — HTTP-response works fine, but produces warnings at compile time:

![image](https://user-images.githubusercontent.com/51654/113108702-f1916580-920d-11eb-9d3f-de12e85471d2.png)

I think changing the type is a bad way to fix this because other functions are reporting about incompatible pointer types passing.

OS: macOS Catalina 10.15.7
gcc:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by onidoru** [comment]
Try this: 

```
char index_html[20]
```

Also here:
```
  ROUTE_GET(uri) {
    char file_name[20];
```


With `*` you create an array of pointers to symbols, and every one of them is not initialized. So there are pointers to potentially random memory addresses that can be already used for any other purposes inside this process.

So basically `file_name` is linked to random memory and you are writing something to that space.

**Comment by foxweb** [comment]
Thanks a lot! Fixed.
