### ISSUE TITLE
Multiple definitions

### ISSUE THREAD

**Issue by zloyvolkey** [foxweb/pico#6]
You have variables definitions in .h file. And when you try to make this project, you already have errors.
`make server
gcc -c -o main.o main.c
gcc -c -o httpd.o httpd.c
gcc -o server main.o httpd.o
/usr/bin/ld: httpd.o:(.bss+0x0): multiple definition of `method'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: httpd.o:(.bss+0x8): multiple definition of `uri'; main.o:(.bss+0x8): first defined here
/usr/bin/ld: httpd.o:(.bss+0x10): multiple definition of `qs'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: httpd.o:(.bss+0x18): multiple definition of `prot'; main.o:(.bss+0x18): first defined here
/usr/bin/ld: httpd.o:(.bss+0x20): multiple definition of `payload'; main.o:(.bss+0x20): first defined here
/usr/bin/ld: httpd.o:(.bss+0x28): multiple definition of `payload_size'; main.o:(.bss+0x28): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:8: server] Error 1
`

**Comment by mocle** [comment]
I just received the same error message.
Any news on that? 

@zloyvolkey  What did you do to be able to use the library anyway?

**Comment by zloyvolkey** [comment]
@mocle Cuz author don't try to test his own code - I don't use this library. I write my own raw tcp client-server library/

**Comment by ToraNova** [comment]
@mocle I was able to compile with the following modifications. using extern declaration in `main.c` and moving the declaration from `httpd.h` into `httpd.c`

`main.c`
```
#include "httpd.h"
#include <stdio.h>

// Client request
extern char     *method,    // "GET" or "POST"
        	*uri,       // "/index.html" things before '?'
        	*qs,        // "a=1&b=2"     things after  '?'
        	*prot;      // "HTTP/1.1"

extern char    *payload;     // for POST
extern int      payload_size;

int main(int c, char** v)
{
	serve_forever("12913");
	return 0;
}

void route()
{
	ROUTE_START()

	ROUTE_GET("/")
	{
		printf("HTTP/1.1 200 OK\r\n\r\n");
		printf("Hello! You are using %s", request_header("User-Agent"));
	}

	ROUTE_POST("/")
	{
		printf("HTTP/1.1 200 OK\r\n\r\n");
		printf("Wow, seems that you POSTed %d bytes. \r\n", payload_size);
		printf("Fetch the data using `payload` variable.");
	}

	ROUTE_END()
}
```

`httpd.h`
```
#ifndef _HTTPD_H_
#define _HTTPD_H_
#include <string.h>

//Server control functions

void serve_forever(const char *PORT);
char *request_header(const char* name);

// user shall implement this function

void route();

// some interesting macro for `route()`
#define ROUTE_START()       if (0) {
#define ROUTE(METHOD,URI)   } else if (strcmp(URI,uri)==0&&strcmp(METHOD,method)==0) {
#define ROUTE_GET(URI)      ROUTE("GET", URI)
#define ROUTE_POST(URI)     ROUTE("POST", URI)
#define ROUTE_END()         } else printf(\
                                "HTTP/1.1 500 Not Handled\r\n\r\n" \
                                "The server has no handler to the request.\r\n" \
                            );

#endif
```

`httpd.c`
```
#define CONNMAX 1000

// Client request
char    *method,    // "GET" or "POST"
        *uri,       // "/index.html" things before '?'
        *qs,        // "a=1&b=2"     things after  '?'
        *prot;      // "HTTP/1.1"

char    *payload;     // for POST
int      payload_size;

static int listenfd, clients[CONNMAX];
/* inserted between the above lines */
```

**Comment by jonathan-rosa** [comment]
> 
> 
> @mocle Cuz author don't try to test his own code - I don't use this library. I write my own raw tcp client-server library/

don't be so mean. and if you wrote your own, it would've been nice if you had it on your git

**Comment by foxweb** [comment]
Fixed!
