### ISSUE TITLE
On Post payload is a zero length string

### ISSUE THREAD

**Issue by TheAgilityCouncil** [foxweb/pico#7]
Hi,

Just tried to do a post to PICO using the following command:
curl -d "url=a" -X POST http://localhost:8000/

Pico reported that 5 bytes was sent. However when I try and printf the string nothing is returned. 
If I do a strlen(payload) this returns 0 bytes.

How do I reference the payload?

Thanks

**Comment by TheAgilityCouncil** [comment]
I managed to fix this error by change the following line: 
`t++;`
to
` t = strtok(NULL, "\r\n");`

**Comment by foxweb** [comment]
Fixed! Thank you!
